// Code generated by mockery v2.45.0. DO NOT EDIT.

package wifi_test

import (
	"fmt"

	wifi "github.com/mdlayher/wifi"
	mock "github.com/stretchr/testify/mock"
)

// WiFiHandle is an autogenerated mock type for the WiFiHandle type
type WiFiHandle struct {
	mock.Mock
}

// Interfaces provides a mock function with given fields:
func (_m *WiFiHandle) Interfaces() ([]*wifi.Interface, error) {
	ret := _m.Called()

@@ -19,39 +21,33 @@ func (_m *WiFiHandle) Interfaces() ([]*wifi.Interface, error) {
	}

	var r0 []*wifi.Interface

	var r1 error

	if rf, ok := ret.Get(0).(func() ([]*wifi.Interface, error)); ok {
		return rf()
	}

	if rf, ok := ret.Get(0).(func() []*wifi.Interface); ok {
		r0 = rf()
	} else if ret.Get(0) != nil {
		if v, ok := ret.Get(0).([]*wifi.Interface); ok {
			r0 = v
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*wifi.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		err := ret.Error(1)
		if err != nil {
			r1 = fmt.Errorf("%w", err)
		}
		r1 = ret.Error(1)
	}

	return r0, r1
}

func NewWiFiHandle(
	t interface {
		mock.TestingT
		Cleanup(f func())
	},
) *WiFiHandle {
// NewWiFiHandle creates a new instance of WiFiHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWiFiHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WiFiHandle {
	mock := &WiFiHandle{}
	mock.Mock.Test(t)
